# Generated by Django 5.2.7 on 2025-10-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_enrolled_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
    ]
